import React, { useState, useMemo } from 'react';
import {
  useProfileStore,
  useAnalyzedJobsStore,
  useEnhancementsStore,
  toast,
} from '@/src/stores';
import { enhanceResume } from '@/src/services/gemini';
import { downloadResumePDF, previewResumeHTML } from '@/src/lib/resume-pdf';
import { Button, Card, CardHeader, CardContent, Badge } from '@/src/components/ui';
import { cn, formatDate } from '@/src/lib/utils';
import { ENHANCEMENT_MODES, SUGGESTION_TYPES, IMPACT_LEVELS } from '@/src/lib/constants';
import type {
  EnhancementMode,
  ResumeEnhancement,
  ResumeAnalysis,
  EnhancementSuggestion,
  EnhancedProfile,
} from '@/src/types';
import {
  Sparkles,
  Target,
  Loader2,
  CheckCircle,
  AlertTriangle,
  ArrowRight,
  FileText,
  Briefcase,
  Code,
  Trophy,
  User,
  TrendingUp,
  Eye,
  Check,
  X,
  ChevronDown,
  ChevronRight,
  BarChart3,
  Lightbulb,
  Download,
  FileDown,
  History,
  Trash2,
  FileType,
  Palette,
  Clock,
} from 'lucide-react';

// Resume download format types
type DownloadFormat = 'markdown' | 'text' | 'json' | 'pdf';
type PDFTemplate = 'professional' | 'modern' | 'minimal';

// Generate resume content in different formats
const generateResumeContent = (
  enhanced: EnhancedProfile,
  profile: any,
  analysis: ResumeAnalysis | null,
  format: DownloadFormat,
  jobInfo?: { company?: string; role?: string }
): string => {
  const timestamp = new Date().toLocaleDateString();

  if (format === 'json') {
    return JSON.stringify(
      {
        generatedAt: timestamp,
        targetJob: jobInfo,
        profile: {
          name: profile.name,
          headline: enhanced.headline,
          summary: enhanced.summary,
          technicalSkills: enhanced.technicalSkills,
          softSkills: enhanced.softSkills,
          experience: enhanced.recentRoles.map((role) => ({
            company: role.company,
            title: role.title,
            duration: role.duration,
            highlights: role.enhancedHighlights,
          })),
          achievements: enhanced.keyAchievements,
        },
        scores: analysis
          ? {
              overall: analysis.overallScore,
              ats: analysis.atsScore,
            }
          : null,
      },
      null,
      2
    );
  }

  if (format === 'markdown') {
    let content = `# ${profile.name}\n\n`;
    content += `**${enhanced.headline}**\n\n`;

    if (enhanced.summary) {
      content += `## Summary\n\n${enhanced.summary}\n\n`;
    }

    if (jobInfo?.role && jobInfo?.company) {
      content += `> *Tailored for: ${jobInfo.role} at ${jobInfo.company}*\n\n`;
    }

    if (analysis) {
      content += `---\n\n`;
      content += `**Resume Scores:** Overall: ${analysis.overallScore}/100 | ATS: ${analysis.atsScore}/100\n\n`;
    }

    content += `## Technical Skills\n\n`;
    content += enhanced.technicalSkills.map((s) => `- ${s}`).join('\n');
    content += `\n\n`;

    if (enhanced.softSkills.length > 0) {
      content += `## Soft Skills\n\n`;
      content += enhanced.softSkills.map((s) => `- ${s}`).join('\n');
      content += `\n\n`;
    }

    content += `## Experience\n\n`;
    enhanced.recentRoles.forEach((role) => {
      content += `### ${role.title}\n`;
      content += `**${role.company}** | ${role.duration}\n\n`;
      role.enhancedHighlights.forEach((h) => {
        content += `- ${h}\n`;
      });
      content += `\n`;
    });

    if (enhanced.keyAchievements && enhanced.keyAchievements.length > 0) {
      content += `## Key Achievements\n\n`;
      enhanced.keyAchievements.forEach((a) => {
        content += `- **${a.description}**`;
        if (a.metrics) content += ` (${a.metrics})`;
        content += `\n`;
      });
    }

    content += `\n---\n*Generated by Job Hunt HQ on ${timestamp}*\n`;

    return content;
  }

  // Plain text format
  let content = `${profile.name.toUpperCase()}\n`;
  content += `${'='.repeat(profile.name.length)}\n\n`;
  content += `${enhanced.headline}\n\n`;

  if (enhanced.summary) {
    content += `SUMMARY\n${'-'.repeat(7)}\n${enhanced.summary}\n\n`;
  }

  if (jobInfo?.role && jobInfo?.company) {
    content += `[Tailored for: ${jobInfo.role} at ${jobInfo.company}]\n\n`;
  }

  if (analysis) {
    content += `Resume Scores: Overall: ${analysis.overallScore}/100 | ATS: ${analysis.atsScore}/100\n\n`;
  }

  content += `TECHNICAL SKILLS\n${'-'.repeat(16)}\n`;
  content += enhanced.technicalSkills.join(', ');
  content += `\n\n`;

  if (enhanced.softSkills.length > 0) {
    content += `SOFT SKILLS\n${'-'.repeat(11)}\n`;
    content += enhanced.softSkills.join(', ');
    content += `\n\n`;
  }

  content += `EXPERIENCE\n${'-'.repeat(10)}\n\n`;
  enhanced.recentRoles.forEach((role) => {
    content += `${role.title}\n`;
    content += `${role.company} | ${role.duration}\n`;
    role.enhancedHighlights.forEach((h) => {
      content += `  • ${h}\n`;
    });
    content += `\n`;
  });

  if (enhanced.keyAchievements && enhanced.keyAchievements.length > 0) {
    content += `KEY ACHIEVEMENTS\n${'-'.repeat(16)}\n`;
    enhanced.keyAchievements.forEach((a) => {
      content += `  • ${a.description}`;
      if (a.metrics) content += ` (${a.metrics})`;
      content += `\n`;
    });
  }

  content += `\n---\nGenerated by Job Hunt HQ on ${timestamp}\n`;

  return content;
};

// Trigger file download
const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Score display component
const ScoreDisplay: React.FC<{ score: number; label: string; size?: 'sm' | 'lg' }> = ({
  score,
  label,
  size = 'sm',
}) => {
  const getScoreColor = (s: number) => {
    if (s >= 80) return 'text-green-400';
    if (s >= 60) return 'text-yellow-400';
    if (s >= 40) return 'text-orange-400';
    return 'text-red-400';
  };

  const getScoreBg = (s: number) => {
    if (s >= 80) return 'bg-green-900/30';
    if (s >= 60) return 'bg-yellow-900/30';
    if (s >= 40) return 'bg-orange-900/30';
    return 'bg-red-900/30';
  };

  return (
    <div className={cn('flex flex-col items-center', size === 'lg' ? 'gap-2' : 'gap-1')}>
      <div
        className={cn(
          'rounded-full flex items-center justify-center font-bold',
          getScoreBg(score),
          getScoreColor(score),
          size === 'lg' ? 'w-20 h-20 text-2xl' : 'w-12 h-12 text-sm'
        )}
      >
        {score}
      </div>
      <span className={cn('text-gray-400', size === 'lg' ? 'text-sm' : 'text-xs')}>{label}</span>
    </div>
  );
};

// Suggestion card component
const SuggestionCard: React.FC<{
  suggestion: EnhancementSuggestion;
  onApply: () => void;
  onDismiss: () => void;
}> = ({ suggestion, onApply, onDismiss }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const typeConfig = SUGGESTION_TYPES.find((t) => t.value === suggestion.type);
  const impactConfig = IMPACT_LEVELS.find((i) => i.value === suggestion.impact);

  const getSectionIcon = () => {
    switch (suggestion.section) {
      case 'headline':
        return <User className="w-4 h-4" />;
      case 'experience':
        return <Briefcase className="w-4 h-4" />;
      case 'skills':
        return <Code className="w-4 h-4" />;
      case 'achievements':
        return <Trophy className="w-4 h-4" />;
      default:
        return <FileText className="w-4 h-4" />;
    }
  };

  return (
    <Card className={cn('transition-all', suggestion.applied && 'opacity-50')}>
      <CardContent className="p-4">
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-gray-400">{getSectionIcon()}</span>
              <Badge className={cn(typeConfig?.bgColor, typeConfig?.color, 'text-xs')}>
                {typeConfig?.label}
              </Badge>
              <Badge className={cn(impactConfig?.bgColor, impactConfig?.color, 'text-xs')}>
                {impactConfig?.label}
              </Badge>
              {suggestion.keywords && suggestion.keywords.length > 0 && (
                <Badge className="bg-cyan-900/30 text-cyan-400 text-xs">
                  +{suggestion.keywords.length} keywords
                </Badge>
              )}
            </div>

            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="flex items-center gap-1 text-sm text-gray-300 hover:text-white mb-2"
            >
              {isExpanded ? (
                <ChevronDown className="w-4 h-4" />
              ) : (
                <ChevronRight className="w-4 h-4" />
              )}
              <span className="font-medium">{suggestion.reason}</span>
            </button>

            {isExpanded && (
              <div className="space-y-3 mt-3">
                <div className="bg-red-900/20 border border-red-800/30 rounded-lg p-3">
                  <div className="text-xs text-red-400 mb-1">Original</div>
                  <p className="text-sm text-gray-300">{suggestion.original}</p>
                </div>
                <div className="flex justify-center">
                  <ArrowRight className="w-4 h-4 text-gray-500" />
                </div>
                <div className="bg-green-900/20 border border-green-800/30 rounded-lg p-3">
                  <div className="text-xs text-green-400 mb-1">Suggested</div>
                  <p className="text-sm text-gray-300">{suggestion.suggested}</p>
                </div>
                {suggestion.keywords && suggestion.keywords.length > 0 && (
                  <div className="flex flex-wrap gap-1">
                    {suggestion.keywords.map((kw, i) => (
                      <Badge key={i} className="bg-cyan-900/30 text-cyan-400 text-xs">
                        {kw}
                      </Badge>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>

          {!suggestion.applied && (
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="ghost"
                onClick={onDismiss}
                className="text-gray-400 hover:text-red-400"
              >
                <X className="w-4 h-4" />
              </Button>
              <Button
                size="sm"
                onClick={onApply}
                className="bg-green-600 hover:bg-green-500 text-white"
              >
                <Check className="w-4 h-4" />
              </Button>
            </div>
          )}

          {suggestion.applied && (
            <Badge className="bg-green-900/30 text-green-400">Applied</Badge>
          )}
        </div>
      </CardContent>
    </Card>
  );
};

// Analysis overview component
const AnalysisOverview: React.FC<{ analysis: ResumeAnalysis }> = ({ analysis }) => {
  const [showDetails, setShowDetails] = useState(false);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-blue-400" />
            <h3 className="font-semibold">Analysis Results</h3>
          </div>
          <Button variant="ghost" size="sm" onClick={() => setShowDetails(!showDetails)}>
            {showDetails ? 'Hide Details' : 'Show Details'}
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex justify-center gap-8">
          <ScoreDisplay score={analysis.overallScore} label="Overall" size="lg" />
          <ScoreDisplay score={analysis.atsScore} label="ATS Score" size="lg" />
        </div>

        <p className="text-sm text-gray-300 text-center">{analysis.summary}</p>

        {showDetails && (
          <div className="space-y-4 pt-4 border-t border-gray-800">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <h4 className="text-sm font-medium text-green-400 mb-2 flex items-center gap-1">
                  <CheckCircle className="w-4 h-4" />
                  Strengths
                </h4>
                <ul className="space-y-1">
                  {analysis.strengthAreas.map((s, i) => (
                    <li key={i} className="text-sm text-gray-400">
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="text-sm font-medium text-yellow-400 mb-2 flex items-center gap-1">
                  <AlertTriangle className="w-4 h-4" />
                  Areas to Improve
                </h4>
                <ul className="space-y-1">
                  {analysis.improvementAreas.map((s, i) => (
                    <li key={i} className="text-sm text-gray-400">
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {analysis.skillsAnalysis && (
              <div className="pt-4 border-t border-gray-800">
                <h4 className="text-sm font-medium text-gray-300 mb-2">Skills Analysis</h4>
                <div className="grid grid-cols-2 gap-4">
                  {analysis.skillsAnalysis.strongMatch.length > 0 && (
                    <div>
                      <div className="text-xs text-green-400 mb-1">Strong Match</div>
                      <div className="flex flex-wrap gap-1">
                        {analysis.skillsAnalysis.strongMatch.slice(0, 8).map((s, i) => (
                          <Badge key={i} className="bg-green-900/30 text-green-400 text-xs">
                            {s}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}
                  {analysis.skillsAnalysis.missing.length > 0 && (
                    <div>
                      <div className="text-xs text-red-400 mb-1">Missing</div>
                      <div className="flex flex-wrap gap-1">
                        {analysis.skillsAnalysis.missing.slice(0, 8).map((s, i) => (
                          <Badge key={i} className="bg-red-900/30 text-red-400 text-xs">
                            {s}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}

            {analysis.experienceRelevance.length > 0 && (
              <div className="pt-4 border-t border-gray-800">
                <h4 className="text-sm font-medium text-gray-300 mb-2">Experience Relevance</h4>
                <div className="space-y-2">
                  {analysis.experienceRelevance.map((exp, i) => (
                    <div
                      key={i}
                      className="flex items-center justify-between bg-gray-800/50 rounded-lg p-2"
                    >
                      <div>
                        <div className="text-sm text-gray-300">{exp.title}</div>
                        <div className="text-xs text-gray-500">{exp.company}</div>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="text-xs text-gray-400">
                          {exp.matchedKeywords.length} keywords
                        </div>
                        <ScoreDisplay score={exp.relevanceScore} label="" />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
};

// Enhanced preview component
const EnhancedPreview: React.FC<{ enhanced: EnhancedProfile; original: any }> = ({
  enhanced,
  original,
}) => {
  const [activeTab, setActiveTab] = useState<'headline' | 'experience' | 'skills'>('headline');

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Eye className="w-5 h-5 text-purple-400" />
          <h3 className="font-semibold">Enhanced Preview</h3>
        </div>
        <div className="flex gap-2 mt-2">
          {(['headline', 'experience', 'skills'] as const).map((tab) => (
            <Button
              key={tab}
              size="sm"
              variant={activeTab === tab ? 'default' : 'ghost'}
              onClick={() => setActiveTab(tab)}
              className="capitalize"
            >
              {tab}
            </Button>
          ))}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {activeTab === 'headline' && (
          <div className="space-y-4">
            <div className="bg-gray-800/50 rounded-lg p-4">
              <div className="text-xs text-gray-500 mb-1">Original</div>
              <p className="text-gray-400">{original.headline}</p>
            </div>
            <div className="bg-green-900/20 border border-green-800/30 rounded-lg p-4">
              <div className="text-xs text-green-400 mb-1">Enhanced</div>
              <p className="text-gray-200">{enhanced.headline}</p>
            </div>
            {enhanced.summary && (
              <div className="bg-blue-900/20 border border-blue-800/30 rounded-lg p-4">
                <div className="text-xs text-blue-400 mb-1">Generated Summary</div>
                <p className="text-sm text-gray-300">{enhanced.summary}</p>
              </div>
            )}
          </div>
        )}

        {activeTab === 'experience' && (
          <div className="space-y-4">
            {enhanced.recentRoles.map((role, i) => (
              <div key={i} className="bg-gray-800/50 rounded-lg p-4">
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <div className="font-medium text-gray-200">{role.title}</div>
                    <div className="text-sm text-gray-400">{role.company}</div>
                  </div>
                  {role.relevanceScore && (
                    <ScoreDisplay score={role.relevanceScore} label="Relevance" />
                  )}
                </div>
                <div className="space-y-2">
                  <div className="text-xs text-gray-500">Enhanced Bullets:</div>
                  <ul className="space-y-1">
                    {role.enhancedHighlights.map((h, j) => (
                      <li key={j} className="text-sm text-gray-300 flex items-start gap-2">
                        <span className="text-green-400 mt-1">*</span>
                        {h}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        )}

        {activeTab === 'skills' && (
          <div className="space-y-4">
            <div>
              <div className="text-sm font-medium text-gray-300 mb-2">Technical Skills</div>
              <div className="flex flex-wrap gap-2">
                {enhanced.technicalSkills.map((skill, i) => (
                  <Badge
                    key={i}
                    className={cn(
                      'text-xs',
                      original.technicalSkills.includes(skill)
                        ? 'bg-gray-700 text-gray-300'
                        : 'bg-green-900/30 text-green-400'
                    )}
                  >
                    {skill}
                    {!original.technicalSkills.includes(skill) && ' (new)'}
                  </Badge>
                ))}
              </div>
            </div>
            {enhanced.softSkills.length > 0 && (
              <div>
                <div className="text-sm font-medium text-gray-300 mb-2">Soft Skills</div>
                <div className="flex flex-wrap gap-2">
                  {enhanced.softSkills.map((skill, i) => (
                    <Badge key={i} className="bg-gray-700 text-gray-300 text-xs">
                      {skill}
                    </Badge>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
};

// History item component
const HistoryItem: React.FC<{
  enhancement: ResumeEnhancement;
  onSelect: () => void;
  onDelete: () => void;
  isSelected: boolean;
}> = ({ enhancement, onSelect, onDelete, isSelected }) => {
  return (
    <div
      className={cn(
        'p-3 rounded-lg border cursor-pointer transition-all',
        isSelected
          ? 'border-purple-500 bg-purple-900/20'
          : 'border-gray-700 hover:border-gray-600 bg-gray-800/50'
      )}
      onClick={onSelect}
    >
      <div className="flex items-start justify-between">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <Badge
              className={cn(
                'text-xs',
                enhancement.mode === 'professional'
                  ? 'bg-purple-900/30 text-purple-400'
                  : 'bg-blue-900/30 text-blue-400'
              )}
            >
              {enhancement.mode === 'professional' ? 'Professional' : 'Tailored'}
            </Badge>
            <div className="flex items-center gap-1 text-xs text-gray-500">
              <Clock className="w-3 h-3" />
              {formatDate(enhancement.createdAt)}
            </div>
          </div>
          {enhancement.companyName && enhancement.jobTitle && (
            <p className="text-sm text-gray-300 truncate">
              {enhancement.jobTitle} @ {enhancement.companyName}
            </p>
          )}
          <div className="flex items-center gap-3 mt-1">
            <span className="text-xs text-gray-500">
              Overall: <span className="text-green-400">{enhancement.analysis.overallScore}</span>
            </span>
            <span className="text-xs text-gray-500">
              ATS: <span className="text-blue-400">{enhancement.analysis.atsScore}</span>
            </span>
          </div>
        </div>
        <Button
          size="sm"
          variant="ghost"
          onClick={(e) => {
            e.stopPropagation();
            onDelete();
          }}
          className="text-gray-500 hover:text-red-400 shrink-0"
        >
          <Trash2 className="w-4 h-4" />
        </Button>
      </div>
    </div>
  );
};

// Main component
export const EnhancePage: React.FC = () => {
  const profile = useProfileStore((s) => s.profile);
  const updateProfile = useProfileStore((s) => s.updateProfile);
  const analyzedJobs = useAnalyzedJobsStore((s) => s.jobs);
  const enhancements = useEnhancementsStore((s) => s.enhancements);
  const addEnhancement = useEnhancementsStore((s) => s.addEnhancement);
  const deleteEnhancement = useEnhancementsStore((s) => s.deleteEnhancement);

  const [mode, setMode] = useState<EnhancementMode>('professional');
  const [selectedJobId, setSelectedJobId] = useState<string>('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showDownloadMenu, setShowDownloadMenu] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [selectedHistoryId, setSelectedHistoryId] = useState<string | null>(null);
  const [pdfTemplate, setPdfTemplate] = useState<PDFTemplate>('professional');
  const [includeScoresInPDF, setIncludeScoresInPDF] = useState(false);

  const [enhancement, setEnhancement] = useState<{
    analysis: ResumeAnalysis;
    suggestions: EnhancementSuggestion[];
    enhancedProfile: EnhancedProfile;
  } | null>(null);

  const selectedJob = useMemo(
    () => analyzedJobs.find((j) => j.id === selectedJobId),
    [analyzedJobs, selectedJobId]
  );

  const isProfileReady =
    profile.name !== 'Senior Engineer' &&
    profile.headline.trim() !== '' &&
    profile.technicalSkills.length > 0;

  const handleAnalyze = async () => {
    if (!isProfileReady) {
      toast.error('Profile incomplete', 'Please fill out your profile first');
      return;
    }

    if (mode === 'job-tailored' && !selectedJob) {
      toast.error('No job selected', 'Please select an analyzed job for tailored enhancement');
      return;
    }

    setIsAnalyzing(true);
    try {
      const result = await enhanceResume({
        profile,
        mode,
        jobDescription: selectedJob?.jobDescription,
        analysis: selectedJob?.analysis,
        company: selectedJob?.company,
        role: selectedJob?.role,
      });

      setEnhancement(result);

      // Save to history
      addEnhancement({
        mode,
        analysis: result.analysis,
        suggestions: result.suggestions,
        enhancedProfile: result.enhancedProfile,
        jobId: selectedJob?.id,
        jobTitle: selectedJob?.role,
        companyName: selectedJob?.company,
      });

      toast.success('Analysis complete', 'Review the suggestions below');
    } catch (error) {
      console.error('Enhancement failed:', error);
      toast.error('Enhancement failed', error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleLoadFromHistory = (historyItem: ResumeEnhancement) => {
    setEnhancement({
      analysis: historyItem.analysis,
      suggestions: historyItem.suggestions,
      enhancedProfile: historyItem.enhancedProfile,
    });
    setSelectedHistoryId(historyItem.id);
    setShowHistory(false);
    toast.success('Loaded from history', 'Previous enhancement loaded');
  };

  const handleDeleteFromHistory = (id: string) => {
    deleteEnhancement(id);
    if (selectedHistoryId === id) {
      setSelectedHistoryId(null);
    }
    toast.success('Deleted', 'Enhancement removed from history');
  };

  const handleApplySuggestion = (suggestionId: string) => {
    if (!enhancement) return;

    setEnhancement((prev) => {
      if (!prev) return null;
      return {
        ...prev,
        suggestions: prev.suggestions.map((s) =>
          s.id === suggestionId ? { ...s, applied: true } : s
        ),
      };
    });
  };

  const handleDismissSuggestion = (suggestionId: string) => {
    if (!enhancement) return;

    setEnhancement((prev) => {
      if (!prev) return null;
      return {
        ...prev,
        suggestions: prev.suggestions.filter((s) => s.id !== suggestionId),
      };
    });
  };

  const handleApplyToProfile = () => {
    if (!enhancement) return;

    updateProfile({ headline: enhancement.enhancedProfile.headline });

    if (enhancement.enhancedProfile.technicalSkills.length > 0) {
      updateProfile({ technicalSkills: enhancement.enhancedProfile.technicalSkills });
    }
    if (enhancement.enhancedProfile.softSkills.length > 0) {
      updateProfile({ softSkills: enhancement.enhancedProfile.softSkills });
    }

    if (enhancement.enhancedProfile.recentRoles.length > 0) {
      const updatedRoles = enhancement.enhancedProfile.recentRoles.map((er) => ({
        company: er.company,
        title: er.title,
        duration: er.duration,
        highlights: er.enhancedHighlights,
      }));
      updateProfile({ recentRoles: updatedRoles });
    }

    toast.success('Profile updated', 'Enhanced content applied to your profile');
  };

  const handleDownload = (format: DownloadFormat) => {
    if (!enhancement) return;

    const jobInfo = selectedJob
      ? { company: selectedJob.company, role: selectedJob.role }
      : undefined;

    if (format === 'pdf') {
      downloadResumePDF({
        enhanced: enhancement.enhancedProfile,
        profile,
        analysis: enhancement.analysis,
        jobInfo,
        template: pdfTemplate,
        includeScores: includeScoresInPDF,
      });
      setShowDownloadMenu(false);
      toast.success('PDF Generated', 'In print dialog, uncheck "Headers and footers" for clean output');
      return;
    }

    const content = generateResumeContent(
      enhancement.enhancedProfile,
      profile,
      enhancement.analysis,
      format,
      jobInfo
    );

    const extensions: Record<string, string> = {
      markdown: 'md',
      text: 'txt',
      json: 'json',
    };

    const mimeTypes: Record<string, string> = {
      markdown: 'text/markdown',
      text: 'text/plain',
      json: 'application/json',
    };

    const baseFilename = selectedJob
      ? `resume-${selectedJob.company?.toLowerCase().replace(/\s+/g, '-') || 'tailored'}`
      : 'resume-enhanced';

    const filename = `${baseFilename}.${extensions[format]}`;
    downloadFile(content, filename, mimeTypes[format]);
    setShowDownloadMenu(false);
    toast.success('Resume downloaded', `Saved as ${filename}`);
  };

  const handlePreviewPDF = () => {
    if (!enhancement) return;

    const jobInfo = selectedJob
      ? { company: selectedJob.company, role: selectedJob.role }
      : undefined;

    previewResumeHTML({
      enhanced: enhancement.enhancedProfile,
      profile,
      analysis: enhancement.analysis,
      jobInfo,
      template: pdfTemplate,
      includeScores: includeScoresInPDF,
    });
  };

  const appliedCount = enhancement?.suggestions.filter((s) => s.applied).length || 0;
  const totalSuggestions = enhancement?.suggestions.length || 0;

  const highImpactSuggestions =
    enhancement?.suggestions.filter((s) => s.impact === 'high' && !s.applied) || [];
  const mediumImpactSuggestions =
    enhancement?.suggestions.filter((s) => s.impact === 'medium' && !s.applied) || [];
  const lowImpactSuggestions =
    enhancement?.suggestions.filter((s) => s.impact === 'low' && !s.applied) || [];

  return (
    <div className="h-full overflow-y-auto">
      <div className="max-w-6xl mx-auto p-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
              <Sparkles className="w-6 h-6 text-purple-400" />
              Resume Enhancement
            </h1>
            <p className="text-gray-400 mt-1">
              AI-powered suggestions to improve your resume for better results
            </p>
          </div>

          <div className="flex items-center gap-2">
            {/* History Button */}
            <Button
              variant="ghost"
              onClick={() => setShowHistory(!showHistory)}
              className={cn(
                'relative',
                showHistory && 'bg-gray-800'
              )}
            >
              <History className="w-4 h-4 mr-2" />
              History
              {enhancements.length > 0 && (
                <Badge className="ml-2 bg-purple-600 text-white text-xs">
                  {enhancements.length}
                </Badge>
              )}
            </Button>

            {/* Download Button */}
            {enhancement && (
              <div className="relative">
                <Button
                  onClick={() => setShowDownloadMenu(!showDownloadMenu)}
                  className="bg-blue-600 hover:bg-blue-500"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download
                  <ChevronDown className="w-4 h-4 ml-2" />
                </Button>

                {showDownloadMenu && (
                  <>
                    <div
                      className="fixed inset-0 z-40"
                      onClick={() => setShowDownloadMenu(false)}
                    />
                    <div className="absolute right-0 mt-2 w-72 bg-gray-800 border border-gray-700 rounded-lg shadow-xl z-50 overflow-hidden">
                      <div className="p-3 border-b border-gray-700">
                        <p className="text-sm font-medium text-gray-200">Download Resume</p>
                        <p className="text-xs text-gray-500">Choose format and options</p>
                      </div>

                      {/* PDF Options */}
                      <div className="p-3 border-b border-gray-700 space-y-3">
                        <div className="flex items-center gap-2 text-sm text-gray-300">
                          <Palette className="w-4 h-4" />
                          <span>PDF Template</span>
                        </div>
                        <div className="flex gap-2">
                          {(['professional', 'modern', 'minimal'] as const).map((t) => (
                            <button
                              key={t}
                              onClick={() => setPdfTemplate(t)}
                              className={cn(
                                'px-3 py-1.5 text-xs rounded-md capitalize transition-colors',
                                pdfTemplate === t
                                  ? 'bg-purple-600 text-white'
                                  : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                              )}
                            >
                              {t}
                            </button>
                          ))}
                        </div>
                        <label className="flex items-center gap-2 text-sm text-gray-400 cursor-pointer">
                          <input
                            type="checkbox"
                            checked={includeScoresInPDF}
                            onChange={(e) => setIncludeScoresInPDF(e.target.checked)}
                            className="rounded border-gray-600 bg-gray-700 text-purple-500"
                          />
                          Include scores in PDF
                        </label>
                      </div>

                      {/* Download Options */}
                      <div className="p-2">
                        <button
                          onClick={() => handleDownload('pdf')}
                          className="w-full flex items-center gap-3 px-3 py-2.5 text-left text-sm text-gray-200 hover:bg-gray-700 rounded-md transition-colors"
                        >
                          <FileType className="w-5 h-5 text-red-400" />
                          <div className="flex-1">
                            <div className="font-medium">PDF Document</div>
                            <div className="text-xs text-gray-500">Uncheck "Headers and footers" in print dialog</div>
                          </div>
                        </button>
                        <button
                          onClick={handlePreviewPDF}
                          className="w-full flex items-center gap-3 px-3 py-2.5 text-left text-sm text-gray-200 hover:bg-gray-700 rounded-md transition-colors"
                        >
                          <Eye className="w-5 h-5 text-purple-400" />
                          <div className="flex-1">
                            <div className="font-medium">Preview PDF</div>
                            <div className="text-xs text-gray-500">See how it looks before downloading</div>
                          </div>
                        </button>

                        <div className="border-t border-gray-700 my-2" />

                        <button
                          onClick={() => handleDownload('markdown')}
                          className="w-full flex items-center gap-3 px-3 py-2 text-left text-sm text-gray-200 hover:bg-gray-700 rounded-md transition-colors"
                        >
                          <FileDown className="w-4 h-4 text-blue-400" />
                          <div>
                            <div className="font-medium">Markdown (.md)</div>
                            <div className="text-xs text-gray-500">Rich formatting, GitHub-ready</div>
                          </div>
                        </button>
                        <button
                          onClick={() => handleDownload('text')}
                          className="w-full flex items-center gap-3 px-3 py-2 text-left text-sm text-gray-200 hover:bg-gray-700 rounded-md transition-colors"
                        >
                          <FileText className="w-4 h-4 text-gray-400" />
                          <div>
                            <div className="font-medium">Plain Text (.txt)</div>
                            <div className="text-xs text-gray-500">ATS-friendly, copy-paste ready</div>
                          </div>
                        </button>
                        <button
                          onClick={() => handleDownload('json')}
                          className="w-full flex items-center gap-3 px-3 py-2 text-left text-sm text-gray-200 hover:bg-gray-700 rounded-md transition-colors"
                        >
                          <Code className="w-4 h-4 text-green-400" />
                          <div>
                            <div className="font-medium">JSON (.json)</div>
                            <div className="text-xs text-gray-500">Structured data, re-import later</div>
                          </div>
                        </button>
                      </div>
                    </div>
                  </>
                )}
              </div>
            )}
          </div>
        </div>

        {/* History Panel */}
        {showHistory && (
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <History className="w-5 h-5 text-purple-400" />
                  <h3 className="font-semibold">Enhancement History</h3>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowHistory(false)}
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              {enhancements.length === 0 ? (
                <div className="text-center py-8 text-gray-500">
                  <History className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>No enhancement history yet</p>
                  <p className="text-sm">Your enhanced resumes will appear here</p>
                </div>
              ) : (
                <div className="grid gap-3 max-h-64 overflow-y-auto">
                  {enhancements.map((item) => (
                    <HistoryItem
                      key={item.id}
                      enhancement={item}
                      onSelect={() => handleLoadFromHistory(item)}
                      onDelete={() => handleDeleteFromHistory(item.id)}
                      isSelected={selectedHistoryId === item.id}
                    />
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Mode Selection */}
        <Card>
          <CardContent className="p-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {ENHANCEMENT_MODES.map((m) => (
                <button
                  key={m.value}
                  onClick={() => setMode(m.value as EnhancementMode)}
                  className={cn(
                    'p-4 rounded-lg border-2 transition-all text-left',
                    mode === m.value
                      ? 'border-purple-500 bg-purple-900/20'
                      : 'border-gray-700 hover:border-gray-600'
                  )}
                >
                  <div className="flex items-center gap-3">
                    {m.value === 'professional' ? (
                      <Sparkles className="w-5 h-5 text-purple-400" />
                    ) : (
                      <Target className="w-5 h-5 text-blue-400" />
                    )}
                    <div>
                      <div className="font-medium text-white">{m.label}</div>
                      <div className="text-sm text-gray-400">{m.description}</div>
                    </div>
                  </div>
                </button>
              ))}
            </div>

            {mode === 'job-tailored' && (
              <div className="mt-4 pt-4 border-t border-gray-800">
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Select an analyzed job to tailor for:
                </label>
                {analyzedJobs.length === 0 ? (
                  <p className="text-sm text-gray-500">
                    No analyzed jobs yet. Go to JD Analyzer to analyze a job first.
                  </p>
                ) : (
                  <select
                    value={selectedJobId}
                    onChange={(e) => setSelectedJobId(e.target.value)}
                    className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-gray-200"
                  >
                    <option value="">Select a job...</option>
                    {analyzedJobs.map((job) => (
                      <option key={job.id} value={job.id}>
                        {job.role || 'Unknown Role'} at {job.company || 'Unknown Company'} (
                        {job.analysis.fitScore}/10)
                      </option>
                    ))}
                  </select>
                )}
              </div>
            )}

            <div className="mt-6 flex justify-center">
              <Button
                onClick={handleAnalyze}
                disabled={isAnalyzing || !isProfileReady}
                className="px-8"
              >
                {isAnalyzing ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 mr-2" />
                    {enhancement ? 'Re-analyze' : 'Analyze & Enhance'}
                  </>
                )}
              </Button>
            </div>

            {!isProfileReady && (
              <p className="text-center text-sm text-yellow-400 mt-4">
                Please complete your profile before analyzing
              </p>
            )}
          </CardContent>
        </Card>

        {/* Results */}
        {enhancement && (
          <>
            {/* Analysis Overview */}
            <AnalysisOverview analysis={enhancement.analysis} />

            {/* Suggestions */}
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Lightbulb className="w-5 h-5 text-yellow-400" />
                    <h3 className="font-semibold">Suggestions</h3>
                    <Badge className="bg-gray-700 text-gray-300">
                      {appliedCount}/{totalSuggestions} applied
                    </Badge>
                  </div>
                  <Button onClick={handleApplyToProfile} className="bg-green-600 hover:bg-green-500">
                    <TrendingUp className="w-4 h-4 mr-2" />
                    Apply All to Profile
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-6">
                {highImpactSuggestions.length > 0 && (
                  <div>
                    <h4 className="text-sm font-medium text-red-400 mb-3 flex items-center gap-2">
                      <AlertTriangle className="w-4 h-4" />
                      High Impact ({highImpactSuggestions.length})
                    </h4>
                    <div className="space-y-3">
                      {highImpactSuggestions.map((s) => (
                        <SuggestionCard
                          key={s.id}
                          suggestion={s}
                          onApply={() => handleApplySuggestion(s.id)}
                          onDismiss={() => handleDismissSuggestion(s.id)}
                        />
                      ))}
                    </div>
                  </div>
                )}

                {mediumImpactSuggestions.length > 0 && (
                  <div>
                    <h4 className="text-sm font-medium text-yellow-400 mb-3 flex items-center gap-2">
                      <TrendingUp className="w-4 h-4" />
                      Medium Impact ({mediumImpactSuggestions.length})
                    </h4>
                    <div className="space-y-3">
                      {mediumImpactSuggestions.map((s) => (
                        <SuggestionCard
                          key={s.id}
                          suggestion={s}
                          onApply={() => handleApplySuggestion(s.id)}
                          onDismiss={() => handleDismissSuggestion(s.id)}
                        />
                      ))}
                    </div>
                  </div>
                )}

                {lowImpactSuggestions.length > 0 && (
                  <div>
                    <h4 className="text-sm font-medium text-gray-400 mb-3">
                      Low Impact ({lowImpactSuggestions.length})
                    </h4>
                    <div className="space-y-3">
                      {lowImpactSuggestions.map((s) => (
                        <SuggestionCard
                          key={s.id}
                          suggestion={s}
                          onApply={() => handleApplySuggestion(s.id)}
                          onDismiss={() => handleDismissSuggestion(s.id)}
                        />
                      ))}
                    </div>
                  </div>
                )}

                {totalSuggestions === 0 && (
                  <div className="text-center py-8 text-gray-500">
                    <CheckCircle className="w-12 h-12 mx-auto mb-3 text-green-400" />
                    <p>Great job! Your resume looks solid.</p>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Enhanced Preview */}
            <EnhancedPreview enhanced={enhancement.enhancedProfile} original={profile} />
          </>
        )}
      </div>
    </div>
  );
};

export default EnhancePage;
